### ISSUE TITLE
Una vez que dos usuarios sean amigos avisar de alguna manera

### ISSUE THREAD

**Issue by matiasquevedo** [romina-cuevas/umbook-2019#4]

**Comment by romina-cuevas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) UMB-3](https://trello.com/c/0He57DO9/3-3-umb-3)

**Comment by juanicastellan0** [comment]
https://github.com/romina-cuevas/umbook-2019/pull/14/files#diff-a518e07b7b176623eb0f989f8920e724
