### ISSUE TITLE
CRUD de grupos (groups)

### ISSUE THREAD

**Issue by matiasquevedo** [romina-cuevas/umbook-2019#6]

**Comment by romina-cuevas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) UMB-5](https://trello.com/c/Au5huIkA/5-5-umb-5)

**Comment by romina-cuevas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) UMB-5](https://trello.com/c/Au5huIkA/5-5-umb-5)

**Comment by romina-cuevas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) UMB-5](https://trello.com/c/Au5huIkA/5-5-umb-5)

**Comment by matiasquevedo** [comment]
![group_users](https://user-images.githubusercontent.com/12038889/57618336-7bbc7c00-7559-11e9-99b0-f11b59f25124.png)
