### ISSUE TITLE
Relacionar grupos con usuarios ()

### ISSUE THREAD

**Issue by matiasquevedo** [romina-cuevas/umbook-2019#7]

**Comment by romina-cuevas** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(5) UMB-5](https://trello.com/c/Au5huIkA/5-5-umb-5)

**Comment by matiasquevedo** [comment]
![group_users](https://user-images.githubusercontent.com/12038889/57618365-8e36b580-7559-11e9-8364-723afc3e5597.png)
